### ISSUE TITLE
EventSub HypeTrain - top_contributions is null

### ISSUE THREAD

**Issue by AlcaDesign** [twurple/twurple#354]
## Bug Report

Apparently the `top_contributions` property on the Hype Train end event can be `null`. The EventSub package assumes it's an array as that's what it documented on Twitch. This property exists for the begin and progress events too but they weren't sent or weren't null. There was no progress events sent by Twitch, only a begin and end.

Here's the data sent by Twitch:
<details>
<summary>channel.hype_train.begin</summary>

```json
{
    "subscription": {
        "id": "XXXXXXXX-XXXX-4XXX-XXXX-XXXXXXXXXXXX",
        "status": "enabled",
        "type": "channel.hype_train.begin",
        "version": "1",
        "condition": {
            "broadcaster_user_id": "1111"
        },
        "transport": {
            "method": "webhook",
            "callback": "https://.../event/channel.hype_train.end.1111"
        },
        "created_at": "2022-04-21T09:41:53.07509807Z",
        "cost": 0
    },
    "event": {
        "id": "XXXXXXXX-XXXX-4XXX-XXXX-XXXXXXXXXXXX",
        "broadcaster_user_id": "1111",
        "broadcaster_user_login": "oneoneoneone",
        "broadcaster_user_name": "OneOneOneOne",
        "total": 400,
        "top_contributions": [
            {
                "user_id": "2222",
                "user_login": "twotwotwotwo",
                "user_name": "twotwotwotwo",
                "type": "bits",
                "total": 200
            }
        ],
        "started_at": "2022-04-24T09:00:00.991366713Z",
        "last_contribution": {
            "user_id": "3333",
            "user_login": "threethreethreethree",
            "user_name": "ThreeThreeThreeThree",
            "type": "bits",
            "total": 100
        },
        "goal": 2000,
        "progress": 400,
        "expires_at": "2022-04-24T09:05:00.991366713Z"
    }
}
```
</details>
<details>
<summary>channel.hype_train.end</summary>

```json
{
    "subscription": {
        "id": "XXXXXXXX-XXXX-4XXX-XXXX-XXXXXXXXXXXX",
        "status": "enabled",
        "type": "channel.hype_train.end",
        "version": "1",
        "condition": {
            "broadcaster_user_id": "1111"
        },
        "transport": {
            "method": "webhook",
            "callback": "https://.../event/channel.hype_train.end.1111"
        },
        "created_at": "2022-04-21T09:41:53.408851211Z",
        "cost": 0
    },
    "event": {
        "id": "XXXXXXXX-XXXX-4XXX-XXXX-XXXXXXXXXXXX",
        "broadcaster_user_id": "1111",
        "broadcaster_user_login": "oneoneoneone",
        "broadcaster_user_name": "OneOneOneOne",
        "total": 400,
        "top_contributions": null,
        "started_at": "2022-04-24T09:00:00.991366713Z",
        "level": 1,
        "ended_at": "2022-04-24T09:05:01.359285382Z",
        "cooldown_ends_at": "2022-04-24T10:05:01.359285382Z"
    }
}
```
</details>

### Code

This is the code in the EventSub package: https://github.com/twurple/twurple/blob/a71eff4e0f050301c3f00f2bae91dd98cee2fc2f/packages/eventsub/src/events/EventSubChannelHypeTrainEndEvent.ts#L86-L90

### Expected behavior

This unexpcted error shouldn't occur. Perhaps `topContributors` should be an empty array as a normalization. A hype train could have no bits or no subs so getting one of those items from the `topContributors` data could be missing anyway (i.e. `.find(n => n.type === 'bits')` when there's no bits contributor).

### Actual Behavior

```js
@/node_modules/@twurple/eventsub/lib/events/EventSubChannelHypeTrainEndEvent.js:63
        return this[common_1.rawDataSymbol].top_contributions.map(data => new EventSubChannelHypeTrainContribution_1.EventSubChannelHypeTrainContribution(data, this._rainContribution(data, this._client));
                                                              ^

TypeError: Cannot read properties of null (reading 'map')
    at EventSubChannelHypeTrainEndEvent.get topContributors [as topContributors] (@/node_modules/@twurple/eventsub/lib/events/EventSubChanntsub/lib/events/EventSubChannelHypeTrainEndEvent.js:63:63)
    at EventSubChannelHypeTrainEndSubscription._handler (@/build/eventsub.js:64:22)
    at EventSubChannelHypeTrainEndSubscription._handleData (@/node_modules/@twurple/eventsub/lib/subscriptions/EventSubSubscription.js:46:s/EventSubSubscription.js:46:14)
    at @/node_modules/@twurple/eventsub/lib/EventSubBase.js:641:46
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Environment

- Version: `5.0.18`
- Node version: `v17.9.0`
- Operating system: `Ubuntu 18.04 on WSL`

**Comment by d-fischer** [comment]
Fixed in version 5.1.4. Thanks for reporting 👍
