### ISSUE TITLE
ClientCredentialsAuthProvider is not a constructor

### ISSUE THREAD

**Issue by Mittelblut9** [twurple/twurple#459]
### Code

```js
const { ClientCredentialsAuthProvider } = require('@twurple/auth');

const authProvider = new ClientCredentialsAuthProvider(clientId, clientSecret);
```

### Expected behavior
The api connects to the twitch api successfully

### Actual Behavior
It crashs

```cmd
const authProvider = new ClientCredentialsAuthProvider(clientId, clientSecret);
                     ^

TypeError: ClientCredentialsAuthProvider is not a constructor
    at Object.<anonymous> (/app/src/events/notfifier/twitch_notifier.js:11:22)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/app/bot/core/core.js:3:29)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
```

### Environment

- Version: 6.0.2
- Node version: 18.8
- Operating system: Linux

**Comment by zunderscore** [comment]
See the v6 migration guide here: https://twurple.js.org/docs/migration/

"The `ClientCredentialsAuthProvider` has been renamed to `AppTokenAuthProvider` to reflect its outcome better. Anything using it will, as before, only support calling APIs using app tokens, not representing any user."

**Comment by d-fischer** [comment]
See above. Closing.
